vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       video: 
            uri_prefix: /images/video
            upload_destination: '%kernel.project_dir%/public/images/video'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        
